# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Select build mode via ENV: JEKYLL_ENV=development / production

# Site settings
title: Dimension Reduction
email: blog@tonylee.hk
description: > # this means to ignore newlines until "baseurl:"
  What is reality?
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hktonylee.github.io" # the base hostname & protocol for your site
image_base: "https://hktonylee.github.io/assets/images"
twitter_username: hktonylee
github_username:  hktonylee

# Build settings
markdown: kramdown

